# Generated by Django 4.2.11 on 2024-11-13 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=200)),
                ('lastName', models.CharField(max_length=200)),
                ('yob', models.DateField()),
                ('gender', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('phone', models.IntegerField()),
                ('address', models.CharField(max_length=200)),
            ],
        ),
    ]
