# Generated by Django 4.2.11 on 2024-11-13 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='age',
        ),
    ]
